WebLayer/Models/ImageUploader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebLayer.Models
{
    public class ImageUploader
    {
        public HttpPostedFileBase file { get; set; }
        public int id { get; set; }
    }
}

WebLayer/Controllers/CostumerController.cs
using EntitiesLayer;
using ServiceLayer.Management;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebLayer.Controllers
{
    public class CostumerController : Controller
    {
        // GET: Suppliers
        private CostumersManagement crud = null;

        public CostumerController()
        {
            crud = new CostumersManagement();
        }

        // GET: Suppliers
        public ActionResult ShowCostumers()
        {
            var costumer = crud.Read().ToList();
            return View(costumer);
        }

        // GET: Register for Products
        public ActionResult AddCostumers()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCostumers(COSTUMERS costumer)
        {
            crud.Create(costumer);
            return RedirectToAction("ShowCostumers");
        }

        // GET: Products edition
        public ActionResult EditCostumers(int Id)
        {
            var costumer = crud.Search(Id);
            return View(costumer);
        }

        [HttpPost]
        public ActionResult EditCostumers(COSTUMERS costumer)
        {
            crud.Update(costumer);
            return RedirectToAction("ShowCostumers");
        }

        public ActionResult DeleteCostumers(int Id)
        {
            crud.Delete(Id);
            return RedirectToAction("ShowCostumers");
        }

        public ActionResult Filter((string field, string value) vals)
        {
            var costumers = crud.Filter(vals.field,vals.value);
            if (costumers.Count > 0)
            {
                return View(costumers);
            }
            else
            {
                return RedirectToAction("ShowCostumers");
            }
        }
    }
}

WebLayer/Controllers/ProductEntriesController.cs
using EntitiesLayer;
using EntitiesLayer.Dtos;
using ServiceLayer;
using ServiceLayer.Management;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebLayer.Controllers
{
    public class ProductEntriesController : Controller
    {
        // GET: ProductEntries
        private ProductEntriesManagement crud = null;

        public ProductEntriesController()
        {
            crud = new ProductEntriesManagement();
        }

        public ActionResult ShowEntries()
        {
            var products = crud.Read();
            return View(products);
        }

        // GET: ProductEntries Add
        public ActionResult AddStock()
        {
            List<ProductDto> products = crud.ProductCatalog();
            List<SelectListItem> ProductsCatalog = products.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Name.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            List<SupplierDto> suppliers = crud.SupplierCatalog();
            List<SelectListItem> SuppliersCatalog = suppliers.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Name.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.ProductsCatalog = ProductsCatalog;
            ViewBag.SuppliersCatalog = SuppliersCatalog;
            return View();
        }

        [HttpPost]
        public ActionResult AddStock(PRODUCT_ENTRIES entry)
        {
            crud.CreateEntry(entry);
            return RedirectToAction("ShowEntries");
        }

        public ActionResult DeleteEntry(int id)
        {
            crud.Delete(id);
            return RedirectToAction("ShowEntries");
        }
    }
}

WebLayer/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceLayer;
using EntitiesLayer;
using System.IO;
using System.Web.Hosting;
using System.Web.UI;
using EntitiesLayer.Dtos;
using WebLayer.Models;

namespace WebLayer.Controllers
{   
    public class ProductsController : Controller
    {
        
        private ProductManagement crud = null;

        public ProductsController() 
        {
            crud = new ProductManagement();
        }

        // GET: Products
        public ActionResult ShowProducts()
        {
            var products = crud.Read();
            return View(products);
        }

        // GET: Register for Products
        public ActionResult AddProducts()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult AddProducts(PRODUCTS product)
        {
            crud.Create(product);
            return RedirectToAction("ShowProducts");
        }

        // GET: Products edition
        public ActionResult EditProducts(int Id)
        {
            var product = crud.Search(Id);
            return View(product);
        }

        [HttpPost]
        public ActionResult EditProducts(PRODUCTS product)
        {
            crud.Update(product);
            return RedirectToAction("ShowProducts");
        }

        public ActionResult DeleteProduct(int Id)
        {
            crud.Delete(Id);
            return RedirectToAction("ShowProducts");
        }
        
        [HttpPost]
        public ActionResult FilterByName(string name) 
        {
            var productos = crud.FilterByName(name);
            return View(productos);
        }

        public ActionResult AddImage(ImageUploader values)
        {
            var products = crud.Read();
            var product = products.Where(p => p.Id == values.id).FirstOrDefault();
            if (values.file != null)
            {
                string pic = product.Name + ".jpg";
                string path = Path.Combine(
                                       Server.MapPath("~/Img"), pic);
                values.file.SaveAs(path);
            }
            return RedirectToAction("ShowProducts");
        }
    }
}

WebLayer/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceLayer;
using ServiceLayer.Management;

namespace WebLayer.Controllers
{
    public class ShopController : Controller
    {
        private readonly ProductManagement crud = new ProductManagement();
        // GET: Shop
        public ActionResult Index()
        {
            var model = crud.ShopRead();
            return View(model);
        }
    }
}

WebLayer/Controllers/SuppliersController.cs
using EntitiesLayer;
using ServiceLayer.Management;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebLayer.Controllers
{
    public class SuppliersController : Controller
    {
        // GET: Suppliers
        private SuppliersManagement crud = null;

        public SuppliersController()
        {
            crud = new SuppliersManagement();
        }

        // GET: Suppliers
        public ActionResult ShowSuppliers()
        {
            var suppliers = crud.Read().ToList();
            return View(suppliers);
        }

        // GET: Register for Products
        public ActionResult AddSuppliers()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSuppliers(SUPPLIERS supplier)
        {
            crud.Create(supplier);
            return RedirectToAction("ShowSuppliers");
        }

        // GET: Products edition
        public ActionResult EditSupplier(int Id)
        {
            var supplier = crud.Search(Id);
            return View(supplier);
        }

        [HttpPost]
        public ActionResult EditSupplier(SUPPLIERS supplier)
        {
            crud.Update(supplier);
            return RedirectToAction("ShowSuppliers");
        }

        public ActionResult DeleteSupplier(int Id)
        {
            crud.Delete(Id);
            return RedirectToAction("ShowSuppliers");
        }
    }
}

WebLayer/Views/Costumer/AddCostumers.cshtml
@model EntitiesLayer.COSTUMERS

@{
    ViewBag.Title = "AddCostumers";
}

<h2>AddCostumers</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>COSTUMERS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RNC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RNC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RNC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                 @Html.DropDownListFor(model => model.Categoty, new List<SelectListItem>
                    {
                          new SelectListItem { Text = "Regular", Value = "Regular", Selected=true},
                          new SelectListItem { Text = "Premium", Value = "Premium"}
                    }, "Select Category", new { @class = "btn btn-default" })

                @Html.ValidationMessageFor(model => model.Categoty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/Costumer/DeleteCostumers.cshtml
@model EntitiesLayer.COSTUMERS

@{
    ViewBag.Title = "DeleteCostumers";
}

<h2>DeleteCostumers</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>COSTUMERS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RNC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RNC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoty)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebLayer/Views/Costumer/EditCostumers.cshtml
@model EntitiesLayer.COSTUMERS

@{
    ViewBag.Title = "EditCostumers";
}

<h2>EditCostumers</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>COSTUMERS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.RNC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RNC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RNC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Categoty, new List<SelectListItem>
                    {
                          new SelectListItem { Text = "Regular", Value = "Regular", Selected=true},
                          new SelectListItem { Text = "Premium", Value = "Premium"}
                    }, "Select Category")
                @Html.ValidationMessageFor(model => model.Categoty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/Costumer/Filter.cshtml
@model IEnumerable<EntitiesLayer.COSTUMERS>

@{
    ViewBag.Title = "Filter";
}

<h2>Filter</h2>

<p>
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RNC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoty)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RNC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoty)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebLayer/Views/Costumer/ShowCostumers.cshtml
@model IEnumerable<EntitiesLayer.COSTUMERS>

@{
    ViewBag.Title = "ShowCostumers";
    
}

<h2>ShowCostumers</h2>

<p>
    @Html.ActionLink("Registrar", "AddCostumers", new {@class="btn btn-primary" })
</p>
<table class="table">
    <tr class="bg-primary">
        <th>
            @Html.DisplayNameFor(model => model.RNC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoty)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RNC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoty)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditCostumers", new { id=item.Id }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Delete", "DeleteCostumers", new { id=item.Id }, new { @class = "btn btn-danger"})
        </td>
    </tr>
}

</table>

WebLayer/Views/ProductEntries/AddStock.cshtml
@model EntitiesLayer.Dtos.StockEntriesDto

@{
    ViewBag.Title = "AddStock";
    List<SelectListItem> products = ViewBag.ProductsCatalog;
    <a href="C:\Users\DEII\source\repos\E_Commerce\DataLayer\packages.config">C:\Users\DEII\source\repos\E_Commerce\DataLayer\packages.config</a>
    List<SelectListItem> suppliers = ViewBag.SuppliersCatalog;
}

<h2>AddStock</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>StockEntriesDto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Product_Id, products, "Select Category", new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.Product_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Supplier_Id, suppliers, "Select Category", new { @class = "btn btn-default" })
                @Html.ValidationMessageFor(model => model.Supplier_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Entry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Entry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Entry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/ProductEntries/ShowEntries.cshtml
@model IEnumerable<EntitiesLayer.Dtos.ProductEntriesDTO>

@{
    ViewBag.Title = "ShowEntries";
}

<h2>ShowEntries</h2>

<p>
    @Html.ActionLink("Nueva Entrada", "AddStock", new { @class = "btn btn-primary"})
</p>
<table class="table">
    <tr class = "bg-primary">
        <th>
            @Html.DisplayNameFor(model => model.Product)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_Entry)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Entry_Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product_Entry)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Entry_Date)
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteEntry", new { id=item.Id }, new { @class = "btn btn-danger"})
        </td>
    </tr> 
}

</table>

WebLayer/Views/Products/AddProducts.cshtml
@model EntitiesLayer.PRODUCTS

@{
    ViewBag.Title = "AddProducts";
    
}

<h2>AddProducts</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PRODUCTS</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/Products/EditProducts.cshtml
@model EntitiesLayer.PRODUCTS

@{
    ViewBag.Title = "EditProducts";
}

<h2>EditProducts</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PRODUCTS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "ShowProducts")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/Products/FilterByName.cshtml
@model IEnumerable<EntitiesLayer.Dtos.ProductDto>

@{
    ViewBag.Title = "FilterByName";
}

<h2>FilterByName</h2>

<table class="table">
    <tr class="bg-primary">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditProducts", new { id=item.Id } , new { @class = "btn btn-success"}) |
            @Html.ActionLink("Delete", "DeleteProduct", new { id=item.Id  }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

WebLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="Glow-Title">
                    <span>S</span>
                    <span>H</span>
                    <span>O</span>
                    <span>P</span>
                    <span>P</span>
                    <span>I</span>
                    <span>N</span>
                    <span>G</span>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="Products">@Html.ActionLink("Productos", "ShowProducts", "Products")</li>
                    <li id="Suppliers">@Html.ActionLink("Proveedores", "ShowSuppliers", "Suppliers")</li>
                    <li id="Costumers">@Html.ActionLink("Clientes", "ShowCostumers", "Costumer")</li>
                    <li id="Costumers">@Html.ActionLink("Entradas", "ShowEntries", "ProductEntries")</li>
                    <li id="Costumers">@Html.ActionLink("Tienda", "Index", "Shop")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    <script>
    
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>